const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "923474719035"
const SESSION_ID = "PRABATH-MD~kHUVQKhA#b1TaTJEJRd1fS0wmASJRG6FEqJNWFfbNNFhm9FBJDjM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
